core/auth/urls.py
from django import urls
from core.auth import views

app_name = 'auth'

urlpatterns = [
    urls.path('log-in', views.LogInView.as_view(), name='log-in'),
    urls.path('log-out', views.LogOutView.as_view(), name='log-out'),
]

core/main/urls.py
from django import urls
from core.main import views

app_name = 'main'

urlpatterns = [
    urls.path('', views.IndexView.as_view(), name='index'),
    urls.path('help', views.HelpView.as_view(), name='help'),
    urls.path('frequently-asked-questions', views.FrequentlyAskedQuestionsView.as_view(), name='frequently-asked-questions'),
]

core/page/urls.py
from django import urls
from core.page import views

app_name = 'page'

urlpatterns = [
    urls.path('', views.IndexView.as_view(), name='index'),
]

core/urls.py
from django import urls

app_name = 'core'

urlpatterns = [
    urls.path('', urls.include('core.main.urls')),
    urls.path('auth/', urls.include('core.auth.urls')),
    urls.path('seminar/', urls.include('core.seminar.urls')),
    urls.path('user/', urls.include('core.user.urls')),
]

main/urls.py
from django import urls

urlpatterns = [
    urls.path('', urls.include('core.page.urls')),
    urls.path('core/', urls.include('core.urls')),
]

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django import urls
from core import utils

class User(AbstractUser):
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.slug
    
    def get_update_url(self):
        return urls.reverse_lazy('core:user:update', args=[self.slug])

    def get_delete_url(self):
        return urls.reverse_lazy('core:user:delete', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = utils.slug_generator(self) if not self.slug else self.slug
        return super().save(*args, **kwargs)

class Seminar(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='seminar_user')
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.slug

    def get_update_url(self):
        return urls.reverse_lazy('core:seminar:update', args=[self.slug])

    def get_delete_url(self):
        return urls.reverse_lazy('core:seminar:delete', args=[self.slug])

    def get_detail_url(self):
        return urls.reverse_lazy('core:seminar:detail', args=[self.slug])
    
    def get_stream_url(self):
        return urls.reverse_lazy('core:seminar:stream', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = utils.slug_generator(self) if not self.slug else self.slug
        return super().save(*args, **kwargs)

class Statistic(models.Model):
    data = models.CharField(max_length=255)
    seminar = models.ForeignKey(Seminar, on_delete=models.CASCADE, related_name='seminar_statistic')
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField()

    def __str__(self):
        return self.slug

    def save(self, *args, **kwargs):
        self.slug = utils.slug_generator(self) if not self.slug else self.slug
        return super().save(*args, **kwargs)

core/seminar/forms.py
from django import forms
from core import models

class SeminarForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name in self.fields:
            self.fields[name].help_text = None
            self.fields[name].widget.attrs.update({
                'class': 'form-control mb-1',
                'autocomplete': 'off',
            })

    class Meta:
        model = models.Seminar
        fields = ['name', 'description']

core/user/forms.py
from django.contrib.auth import forms
from core import models

class UserCreationForm(forms.UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name in self.fields:
            self.fields[name].help_text = None
            self.fields[name].widget.attrs.update({
                'class': 'form-control mb-1',
                'autocomplete': 'off',
            })

    class Meta:
        model = models.User
        fields = ['first_name', 'last_name', 'username', 'password1', 'password2']

class UserChangeForm(forms.UserChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name in self.fields:
            self.fields[name].help_text = None
            self.fields[name].widget.attrs.update({
                'class': 'form-control mb-1',
                'autocomplete': 'off',
            })

    class Meta:
        model = models.User
        fields = ['first_name', 'last_name', 'username']

core/main/views.py
from django.contrib.auth import mixins
from django.views import generic
from core import models

class IndexView(mixins.LoginRequiredMixin, generic.TemplateView):
    template_name = 'core/main/index.html'
    extra_context = {'title':'Dashboard'}

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
class HelpView(mixins.LoginRequiredMixin, generic.TemplateView):
    template_name = 'core/main/help.html'
    extra_context = {'title': 'Help'}

class FrequentlyAskedQuestionsView(mixins.LoginRequiredMixin, generic.TemplateView):
    template_name = 'core/main/frequently-asked-questions.html'
    extra_context = {'title': 'Frequently Asked Questions'}

core/page/views.py
from django.views import generic

class IndexView(generic.TemplateView):
    template_name = 'page/index.html'
    extra_context = {'title': 'Sface'}

class AboutView(generic.TemplateView):
    template_name = 'page/about.html'
    extra_context = {'title': 'About'}

class ContactView(generic.TemplateView):
    template_name = 'page/contact.html'
    extra_context = {'title': 'Contact'}

class PrivacyPolicyView(generic.TemplateView):
    template_name = 'page/privacy-policy.html'
    extra_context = {'title': 'Privacy Policy'}

core/seminar/views.py
from django.contrib.auth import mixins
from django.views import generic
from django import urls, http
from django.contrib import messages
from core import models
from core.seminar import forms
import json

class IndexView(mixins.LoginRequiredMixin, generic.ListView):
    model = models.Seminar
    template_name = 'core/seminar/index.html'
    extra_context = {'title': 'Seminar'}

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user).order_by('-created_at')
    
class CreateView(mixins.LoginRequiredMixin, generic.CreateView):
    model = models.Seminar
    template_name = 'core/form.html'
    form_class = forms.SeminarForm
    success_url = urls.reverse_lazy('core:seminar:index')
    extra_context = {
        'title': 'Create Seminar',
        'action':urls.reverse_lazy('core:seminar:create'),
    }

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        messages.info(self.request, f'Seminar created successfully.')
        return http.HttpResponse(status=204, headers={
            'HX-Trigger': json.dumps({
                'form': {'path': str(self.success_url),}
            }),
        })
    
class UpdateView(mixins.LoginRequiredMixin, generic.UpdateView):
    model = models.Seminar
    template_name = 'core/form.html'
    form_class = forms.SeminarForm
    success_url = urls.reverse_lazy('core:seminar:index')
    extra_context = {'title': 'Update Seminar'}
    query_pk_and_slug = True

    def dispatch(self, *args, **kwargs):
        if self.get_object().user != self.request.user:
            return self.handle_no_permission()
        self.extra_context['action'] = self.get_object().get_update_url
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        object = form.save()
        messages.info(self.request, f'Seminar updated successfully.')
        return http.HttpResponse(status=204, headers={
            'HX-Trigger': json.dumps({
                'form': {'path': str(self.success_url),}
            }),
        })
    
class DeleteView(mixins.LoginRequiredMixin, generic.DeleteView):
    model = models.Seminar
    template_name = 'core/delete.html'
    success_url = urls.reverse_lazy('core:seminar:index')
    extra_context = {'title': 'Delete Seminar'}
    query_pk_and_slug = True

    def dispatch(self, *args, **kwargs):
        if self.get_object().user != self.request.user:
            return self.handle_no_permission()
        self.extra_context['action'] = self.get_object().get_delete_url
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        object = self.get_object()
        object.delete()
        messages.info(self.request, f'Seminar deleted successfully.')
        return http.HttpResponse(status=204, headers={
            'HX-Trigger': json.dumps({
                'form': {'path': str(self.success_url),}
            }),
        })
    
class DetailView(mixins.LoginRequiredMixin, generic.DetailView):
    model = models.Seminar
    template_name = 'core/seminar/detail.html'
    extra_context = {}
    query_pk_and_slug = True

    def dispatch(self, *args, **kwargs):
        if self.get_object().user != self.request.user:
            return self.handle_no_permission()
        self.extra_context['title'] = str(self.get_object().name)
        self.extra_context['data'] = [{'data': eval(object.data), 'created_at': object.created_at.isoformat()} for object in models.Statistic.objects.filter(seminar=self.get_object())]
        return super().dispatch(*args, **kwargs)

class StreamView(mixins.LoginRequiredMixin, generic.DetailView):
    model = models.Seminar
    template_name = 'core/seminar/stream.html'
    extra_context = {}
    query_pk_and_slug = True

    def dispatch(self, *args, **kwargs):
        if self.get_object().user != self.request.user:
            return self.handle_no_permission()
        self.extra_context['title'] = str(self.get_object().name).capitalize()
        self.extra_context['websocket'] = self.request.build_absolute_uri().replace('http', 'ws')
        return super().dispatch(*args, **kwargs)

core/user/views.py
from django.contrib.auth import mixins
from django.views import generic
from django import urls, http
from django.contrib import messages
from core import models, utils
from core.user import forms
import json

class IndexView(mixins.LoginRequiredMixin, generic.ListView):
    model = models.User
    template_name = 'core/user/index.html'
    extra_context = {'title': 'User'}

    def get_queryset(self):
        if not self.request.user.is_superuser:
            return self.handle_no_permission()
        return super().get_queryset().filter(is_superuser=False).order_by('-created_at')
    
class CreateView(mixins.LoginRequiredMixin, generic.CreateView):
    model = models.User
    template_name = 'core/form.html'
    form_class = forms.UserCreationForm
    success_url = urls.reverse_lazy('core:user:index')
    extra_context = {
        'title': 'Create User',
        'action': urls.reverse_lazy('core:user:create'),
    }

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_superuser:
            return self.handle_no_permission()
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        object = form.save()
        messages.info(self.request, f'User created successfully.')
        return http.HttpResponse(status=204, headers={
            'HX-Trigger': json.dumps({
                'form': {'path': str(self.success_url),}
            }),
        })
    
class UpdateView(mixins.LoginRequiredMixin, generic.UpdateView):
    model = models.User
    template_name = 'core/form.html'
    form_class = forms.UserChangeForm
    success_url = urls.reverse_lazy('core:user:index')
    extra_context = {'title': 'Update User'}
    query_pk_and_slug = True

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_superuser:
            return self.handle_no_permission()
        self.extra_context['action'] = self.get_object().get_update_url
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        object = form.save()
        messages.info(self.request, f'User updated successfully.')
        return http.HttpResponse(status=204, headers={
            'HX-Trigger': json.dumps({
                'form': {'path': str(self.success_url),}
            }),
        })
    
class DeleteView(mixins.LoginRequiredMixin, generic.DeleteView):
    model = models.User
    template_name = 'core/delete.html'
    success_url = urls.reverse_lazy('core:user:index')
    extra_context = {'title': 'Delete User'}
    query_pk_and_slug = True

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_superuser:
            return self.handle_no_permission()
        self.extra_context['action'] = self.get_object().get_delete_url
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        object = self.get_object()
        object.delete()
        messages.info(self.request, f'User deleted successfully.')
        return http.HttpResponse(status=204, headers={
            'HX-Trigger': json.dumps({
                'form': {'path': str(self.success_url),}
            }),
        })

templates/core/base.html
{% extends 'main.html' %}
{% load static %}

{% block main %}
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
                <div class="app-brand demo">
                    <a href="{% url 'page:index' %}" class="app-brand-link">
                        <span class="app-brand-logo demo">
                            <!-- <svg width="25" viewBox="0 0 25 42" ... > ... </svg> -->
                        </span>
                        <span class="app-brand-text demo menu-text fw-bold ms-2 text-uppercase">Sface</span>
                    </a>
                    <a href="javascript:void(0)" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
                        <i class="bx bx-chevron-left bx-sm align-middle"></i>
                    </a>
                </div>
                <div class="menu-inner-shadow"></div>
                <ul class="menu-inner py-1">
                    <li class="menu-header small text-uppercase">
                        <span class="menu-header-text">Menu</span>
                    </li>
                    <li class="menu-item">
                        <a href="javascript:void(0)" class="menu-link" hx-get="{% url 'core:main:index' %}" hx-target="#base" hx-push-url="true">
                            <i class="menu-icon tf-icons bx bxs-dashboard"></i>
                            <div data-i18n="Dashboard">Dashboard</div>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a href="javascript:void(0)" class="menu-link" hx-get="{% url 'core:seminar:index' %}" hx-target="#base" hx-push-url="true">
                            <i class="menu-icon tf-icons bx bxs-calendar-alt"></i>
                            <div data-i18n="Seminar">Seminar</div>
                        </a>
                    </li>
                    {% if request.user.is_superuser %}
                        <li class="menu-item">
                            <a href="javascript:void(0)" class="menu-link" hx-get="{% url 'core:user:index' %}" hx-target="#base" hx-push-url="true">
                                <i class="menu-icon tf-icons bx bxs-group"></i>
                                <div data-i18n="User">User</div>
                            </a>
                        </li>                         
                    {% endif %}
                    <li class="menu-header small text-uppercase">
                        <span class="menu-header-text">Misc</span>
                    </li>
                    <li class="menu-item">
                        <a href="javascript:void(0)" class="menu-link" hx-get="{% url 'core:main:help' %}" hx-target="#base" hx-push-url="true">
                            <i class="menu-icon tf-icons bx bxs-help-circle"></i>
                            <div data-i18n="Help">Help</div>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a href="javascript:void(0)" class="menu-link" hx-get="{% url 'core:main:frequently-asked-questions' %}" hx-target="#base" hx-push-url="true">
                            <i class="menu-icon tf-icons bx bx-question-mark"></i>
                            <div data-i18n="FAQ">FAQ</div>
                        </a>
                    </li>
                </ul>
            </aside>
            <div class="layout-page">
                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>
                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                        <div class="navbar-nav align-items-center">
                            <div class="nav-item d-flex align-items-center">
                                <i class="bx bx-search fs-4 lh-0"></i>
                                <input type="text" class="form-control border-0 shadow-none ps-1 ps-sm-2" placeholder="Search..." aria-label="Search...">
                            </div>
                        </div>
                        <ul class="navbar-nav flex-row align-items-center ms-auto">
                            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0)" data-bs-toggle="dropdown">
                                    <div class="avatar avatar-online">
                                        <img src="{% static 'assets/img/avatars/1.png' %}" alt="User Profile" class="w-px-40 h-auto rounded-circle">
                                    </div>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li>
                                        <a class="dropdown-item" href="javascript:void(0)">
                                            <div class="d-flex">
                                                <div class="flex-shrink-0 me-3">
                                                    <div class="avatar avatar-online">
                                                        <img src="{% static 'assets/img/avatars/1.png' %}" alt="User Profile" class="w-px-40 h-auto rounded-circle">
                                                    </div>
                                                </div>
                                                <div class="flex-grow-1">
                                                    <span class="fw-medium d-block">
                                                        <span>{{ request.user.first_name }} {{ request.user.last_name }}</span>
                                                    </span>
                                                    <small class="text-muted">
                                                        {% if request.user.is_superuser %}
                                                            <span>Superuser</span>
                                                        {% else %}
                                                            <span>User</span>
                                                        {% endif %}
                                                    </small>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <div class="dropdown-divider"></div>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="javascript:void(0)">
                                            <i class="bx bx-user me-2"></i>
                                            <span class="align-middle">My Profile</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="javascript:void(0)">
                                            <i class="bx bx-cog me-2"></i>
                                            <span class="align-middle">Settings</span>
                                        </a>
                                    </li>
                                    <li>
                                        <div class="dropdown-divider"></div>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="javascript:void(0)" hx-get="{% url 'core:auth:log-out' %}" hx-target="#modal-content" data-bs-toggle="modal" data-bs-target="#modal">
                                            <i class="bx bx-power-off me-2"></i>
                                            <span class="align-middle">Log Out</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="content-wrapper">
                    <div class="container-xxl flex-grow-1 container-p-y">
                        <div id="base" hx-swap-oob="true">
                            {% if messages %}
                                {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                                    {{ message|safe }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                                {% endfor %}
                            {% endif %}
                            {% block base %}{% endblock base %}
                            <div class="modal fade" id="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content" id="modal-content" hx-swap-oob="true"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <footer class="content-footer footer bg-footer-theme">
                        <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                            <div class="mb-2 mb-md-0">
                                © <script>document.write(new Date().getFullYear())</script>
                            </div>
                        </div>
                    </footer>
                    <div class="content-backdrop fade"></div>
                </div>
            </div>
        </div>
        <div class="layout-overlay layout-menu-toggle"></div>
    </div>
{% endblock main %}

templates/core/delete.html
<form hx-post="{{ action }}" hx-target="#modal-content">
    <div class="modal-header">
        <h5 class="modal-title">{{ title }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
    </div>
    <div class="modal-body">
        {% csrf_token %}
        <p>Are you sure you want to delete this data?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Confirm</button>
    </div>
</form>

templates/core/form.html
<form hx-post="{{ action }}" hx-target="#modal-content">
    <div class="modal-header">
        <h5 class="modal-title">{{ title }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
    </div>
    <div class="modal-body">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
            <label class="form-label text-uppercase">{{ field.label }}</label>
            {{ field }}
            <span class="text-danger">
                {% for error in field.errors %}
                    {{ error }}
                {% endfor %}
            </span>
        </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>